services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - REACT_APP_RUM_APPLICATION_ID=<YOUR_RUM_APPLICATION_ID>
      - REACT_APP_RUM_CLIENT_TOKEN=<YOUR_RUM_CLIENT_TOKEN>
      - REACT_APP_RUM_DD_SITE=datadoghq.com
      - REACT_APP_RUM_VERSION=1.0.0
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/react-mongo-template-docker
      - DD_AGENT_HOST=datadog-agent
      - DD_TRACE_AGENT_PORT=8126

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  datadog-agent:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=<YOUR_DATADOG_API_KEY>
      - DD_LOGS_ENABLED=true
      - DD_APM_ENABLED=true
      - DD_PROCESS_AGENT_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    ports:
      - "8126:8126/tcp"
volumes:
  mongo-data: